// Mocks generated by Mockito 5.3.0 from annotations
// in smile_front/test/app/modules/auth/infra/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smile_front/app/modules/auth/infra/datasource/auth_datasource_interface.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthDatasourceInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDatasourceInterface extends _i1.Mock
    implements _i2.AuthDatasourceInterface {
  MockAuthDatasourceInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getAccessLevel(String? user) =>
      (super.noSuchMethod(Invocation.method(#getAccessLevel, [user]),
          returnValue: _i3.Future<String>.value('')) as _i3.Future<String>);
  @override
  _i3.Future<Map<String, dynamic>> login(String? user, String? password) =>
      (super.noSuchMethod(Invocation.method(#login, [user, password]),
              returnValue:
                  _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> refreshToken(String? token) =>
      (super.noSuchMethod(Invocation.method(#refreshToken, [token]),
              returnValue:
                  _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
}
