name: smile_front
description: Smile 2023.

publish_to: "none"

version: 1.6.59+119

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fluttericon: ^2.0.0
  flutter_modular: ^3.4.1+1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+1
  flutter_typeahead: ^4.0.0
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.6
  mask_text_input_formatter: ^2.4.0
  enum_to_string: ^2.0.1
  syncfusion_flutter_datepicker: ^19.4.56
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  video_player: ^2.4.0
  url_launcher: ^6.1.5
  string_validator: ^0.3.0
  getwidget: ^2.0.4
  email_validator: ^2.1.17
  network_image_mock: ^2.1.1
  change_app_package_name: ^1.1.0
  flutter_html: ^2.2.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_modular_test: ^1.0.4
  mockito: ^5.0.10
  lints: ^2.0.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

scripts:
  mobx_build: flutter pub run build_runner build
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs
flutter_intl:
  enabled: true
