name: smile_front
description: Smile 2022.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  flutter_modular: ^3.4.1
  rxdart: ^0.27.2
  google_fonts: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  mobx: ^2.0.5
  flutter_mobx: ^2.0.0
  flutter_typeahead: ^3.1.3
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  mask_text_input_formatter: ^2.1.0
  enum_to_string: ^2.0.1
  syncfusion_flutter_datepicker: ^19.4.56
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0

dev_dependencies:
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_modular_test: ^1.0.4
  mockito: ^5.0.10
  lints: ^1.0.1
  pedantic: ^1.11.1
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

scripts:
  mobx_build: flutter pub run build_runner build
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs