// Mocks generated by Mockito 5.0.16 from annotations
// in smile_front/test/app/modules/dashboard/controller/dashboard_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smile_front/app/modules/dashboard/domain/entities/activity.dart'
    as _i4;
import 'package:smile_front/app/modules/dashboard/domain/infra/activity_enum.dart'
    as _i5;
import 'package:smile_front/app/modules/dashboard/domain/repositories/activities_repository_interface.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ActivitiesRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockActivitiesRepositoryInterface extends _i1.Mock
    implements _i2.ActivitiesRepositoryInterface {
  MockActivitiesRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Activity>> getActivities(
          _i5.ActivityEnum? activityEnum) =>
      (super.noSuchMethod(Invocation.method(#getActivities, [activityEnum]),
              returnValue: Future<List<_i4.Activity>>.value(<_i4.Activity>[]))
          as _i3.Future<List<_i4.Activity>>);
  // @override
  // String toString() => super.toString();
}
