// Mocks generated by Mockito 5.3.2 from annotations
// in smile_front/test/app/modules/dashboard/presenter/controller/adm/adm_dashboard_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smile_front/app/modules/dashboard/domain/usecases/delete_activity.dart'
    as _i4;
import 'package:smile_front/app/modules/dashboard/domain/usecases/get_admin_activities_interface.dart'
    as _i5;
import 'package:smile_front/app/modules/dashboard/domain/usecases/get_download_link_csv.dart'
    as _i2;
import 'package:smile_front/app/modules/dashboard/domain/usecases/manual_drop_activity.dart'
    as _i7;
import 'package:smile_front/app/shared/models/admin_activity_model.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetDownloadLinkCsvInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDownloadLinkCsvInterface extends _i1.Mock
    implements _i2.GetDownloadLinkCsvInterface {
  MockGetDownloadLinkCsvInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}

/// A class which mocks [DeleteActivityInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteActivityInterface extends _i1.Mock
    implements _i4.DeleteActivityInterface {
  MockDeleteActivityInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> call(String? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}

/// A class which mocks [GetAdminActivitiesInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAdminActivitiesInterface extends _i1.Mock
    implements _i5.GetAdminActivitiesInterface {
  MockGetAdminActivitiesInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.AdminActivityModel>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i3.Future<List<_i6.AdminActivityModel>>.value(
            <_i6.AdminActivityModel>[]),
      ) as _i3.Future<List<_i6.AdminActivityModel>>);
}

/// A class which mocks [ManualDropActivityInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockManualDropActivityInterface extends _i1.Mock
    implements _i7.ManualDropActivityInterface {
  MockManualDropActivityInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> call(
    String? activityCode,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            activityCode,
            userId,
          ],
        ),
        returnValue: _i3.Future<dynamic>.value(),
      ) as _i3.Future<dynamic>);
}
