// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALQsK3VSz1_R9x8TJmw6uO7lwqRyhAJTs',
    appId: '1:272148621093:web:21e6054d9a5e31e7e95ccc',
    messagingSenderId: '272148621093',
    projectId: 'smile-front',
    authDomain: 'smile-front.firebaseapp.com',
    storageBucket: 'smile-front.appspot.com',
    measurementId: 'G-7XWJZ0CP9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDir4A5nduA4ynLWDxE2NZ5JC-uiJgw7wQ',
    appId: '1:272148621093:android:a5bb04748b34ae29e95ccc',
    messagingSenderId: '272148621093',
    projectId: 'smile-front',
    storageBucket: 'smile-front.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjDK91v16je_xBFULO6BCvTEBHzt0bpmw',
    appId: '1:272148621093:ios:f556f80cef6965b1e95ccc',
    messagingSenderId: '272148621093',
    projectId: 'smile-front',
    storageBucket: 'smile-front.appspot.com',
    iosClientId:
        '272148621093-81eisinrmcia6sntu65hfv7g9dgn5et1.apps.googleusercontent.com',
    iosBundleId: 'com.example.smileFront',
  );
}
