// Mocks generated by Mockito 5.1.0 from annotations
// in smile_front/test/app/modules/logged-adm-home/infra/repositories/future_activity_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smile_front/app/modules/logged-adm-home/infra/datasources/future_activity_datasource.dart'
    as _i3;
import 'package:smile_front/app/shared/entities/activity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeActivity_0 extends _i1.Fake implements _i2.Activity {}

/// A class which mocks [FutureActivityDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFutureActivityDatasource extends _i1.Mock
    implements _i3.FutureActivityDatasource {
  MockFutureActivityDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Activity> getFutureActivity() =>
      (super.noSuchMethod(Invocation.method(#getFutureActivity, []),
              returnValue: Future<_i2.Activity>.value(_FakeActivity_0()))
          as _i4.Future<_i2.Activity>);
}
