default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to TestFlight"
  lane :homolog do
    api_key = app_store_connect_api_key(
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_content: ENV['API_PRIVATE_KEY'],
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    upload_to_testflight(
      api_key: api_key,
      skip_submission: true,
      ipa: ENV['APP_PATH'],
      skip_waiting_for_build_processing: true,
    )
  end

end
