// Mocks generated by Mockito 5.4.0 from annotations
// in smile_front/test/app/modules/resend-confirmation/presenter/controller/resend_confirmation_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smile_front/app/modules/resend-confirmation/domain/repository/resend_confirmation_datasource_interface.dart'
    as _i2;
import 'package:smile_front/app/modules/resend-confirmation/domain/usecases/resend_confirmation.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ResendConfirmationRepositoryInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendConfirmationRepositoryInterface extends _i1.Mock
    implements _i2.ResendConfirmationRepositoryInterface {
  MockResendConfirmationRepositoryInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> resendConfirmation(String? username) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendConfirmation,
          [username],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}

/// A class which mocks [ResendConfirmationInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockResendConfirmationInterface extends _i1.Mock
    implements _i4.ResendConfirmationInterface {
  MockResendConfirmationInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> call(String? username) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [username],
        ),
        returnValue: _i3.Future<String>.value(''),
      ) as _i3.Future<String>);
}
