name: Build & Deploy to App Store and Testflight
on:
  push:
  #   paths:
  #     - 'pubspec.yaml'
  #   branches:
  #     - homolog
  #     - prod

jobs:
  build_IOS_App:
    name: Build IOS App
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter Version
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: ios

      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.9.0
        with:
          project-path: ios/Runner.xcodeproj
          workspace-path: ios/Runner.xcworkspace
          team-id: ${{ secrets.TEAM_ID }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          p12-base64: ${{ secrets.P12_KEY }}
          certificate-password: ${{ secrets.PW_CERT }}
          export-method: ${{ vars.EXPORT_METHOD }}
          code-signing-identity: ${{ vars.CODE_SIGNING_IDENTITY }}

      - name: Exec fastlane
        run: bundle exec fastlane homolog
        env:
          APP_PATH: /Users/runner/work/smile_front/smile_front/output.ipa
          ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        working-directory: ios
