name: Build & Deploy to Play Store
on:
  push:
    paths-ignore:
      - 'pubspec.yaml'
      - '**/.github/*'
    branches:
      - develop

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: bump version number
        run: |
          old_v=$(cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)
          echo "old_version=$old_v" >> $GITHUB_ENV

          perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/($1).($2+1)/e' pubspec.yaml

          version=$(cat pubspec.yaml | grep -o 'version:[^:]*' | cut -f2 -d":" | xargs)
          echo "new_version=$version" >> $GITHUB_ENV

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_USER: ${{ github.actor }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_USER }}"
          git config --global user.email "${{ env.CI_COMMIT_USER }}@users.noreply.github.com"
          git commit -a -m "bump version from ${{ env.old_version }} to ${{ env.new_version}}"
          git push

  fastlane-deploy_play_store:
    needs: bump_version
    name: Build & Deploy to Play Store
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
        id-token: write
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter Version
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get flutter dependencies
        run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android

      - name: Build appbundle
        run: flutter build appbundle --release --dart-define=MSS_USER_BASE_URL=${{vars.MSS_USERS_ENDPOINT}} --dart-define=MSS_ACTIVITIES_BASE_URL=${{vars.MSS_ACTIVITIES_ENDPOINT}} --dart-define=S3_BASE_URL=${{vars.AWS_BUCKET_ASSETS}} --dart-define=SPONSOR_FORM_REQUEST_URL=${{vars.SPONSOR_FORM_REQUEST_URL}} --dart-define=ENV=${{vars.ENV}}

      - name: exec fastlane
        run: bundle exec fastlane ${{ github.ref_name }}
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android