# This is a basic workflow to help you get started with Actions

name: CD_AWS_S3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ homolog, develop, prod ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_WEB:
      name: Build Flutter (WEB)
      runs-on: ubuntu-latest
      environment: ${{ github.ref_name }}
      permissions:
        id-token: write
        contents: write


      steps:
         - name: Checkout code
           uses: actions/checkout@v2
         - name: Setup Java Version
           uses: actions/setup-java@v1
           with:
             java-version: "12.x"
         - name: Setup Flutter Version
           uses: subosito/flutter-action@v1
           with:
             flutter-version: '3.3.10'
             channel: "stable"
         - name: Get flutter dependencies
           run: flutter pub get
           
         - name: rename sw file
           if: github.ref == 'refs/heads/prod'
           run: mv web/firebase-messaging-sw-prod.js web/firebase-messaging-sw.js
           
         - name: Setup AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-region: us-east-1
             role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
             role-session-name: github-action
          
         - run: flutter build web -t lib/${{secrets.MAIN_FLAVOR}}.dart --web-renderer canvaskit --release --dart-define=MSS_USER_BASE_URL=${{secrets.MSS_USERS_ENDPOINT}} --dart-define=MSS_ACTIVITIES_BASE_URL=${{secrets.MSS_ACTIVITIES_ENDPOINT}} --dart-define=S3_BASE_URL=https://d3ebnpochj0915.cloudfront.net/ --dart-define=MSS_CERTIFICATE_BASE_URL=https://gywf2oepfesleyuhgpwj5humz40bguxi.lambda-url.sa-east-1.on.aws/ --dart-define=SPONSOR_FORM_REQUEST_URL=${{secrets.SPONSOR_FORM_REQUEST_URL}} --dart-define=ENV=${{secrets.ENV}}

#          - name: Upload to S3
#            uses: shallwefootball/s3-upload-action@master
#            with:
#              aws_key_id: ${{ secrets.AWS_KEY_ID }}
#              aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
#              aws_bucket: ${{ secrets.AWS_BUCKET }}
#              source_dir: 'build/web'
#              destination_dir: ''
             
         - name: Upload to S3
           run: aws s3 cp build/web s3://${{ secrets.AWS_BUCKET }}/ --recursive --region ${{ vars.AWS_S3_BUCKET_REGION }}
             
         - name: Clear CDN cache
           run: aws cloudfront create-invalidation --distribution-id ${{secrets.CLOUD_FRONT_ID}} --paths "/*" --region ${{ secrets.AWS_DEFAULT_REGION }}
           env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
