name: CD Dev

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
jobs:
  build_Android_App:
    name: Build APP Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java Version
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter Version
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Android Build APK
        run: flutter build apk --split-per-abi

      - name: Android Build APPBundle
        run: flutter build appbundle
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DignusApp-Android
          path: |
            build/app/outputs/bundle/release/app-release.aab
            build/app/outputs/apk/release/*.apk
  deploy_dev:
    name: Firebase App Distribution
    if: github.event.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: [build_Android_App]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download a artifact
        id: download-artifact
        uses: actions/download-artifact@v2
        with:
          name: DignusApp-Android

      - name: Firebase App Distribution Android
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: dev-front, dev-back, dev-community
          file: apk/release/app-arm64-v8a-release.apk
          debug: true
