name: Check & Create PR

on:
  push:
    branches:
      - develop
      - homolog

jobs:
  pull_request:
    uses: maua-dev/ci_workflows_reusable/.github/workflows/pull_request.yml@main
    with:
      repository: ${{ github.repository }}